name: Auto-fetch Old World RSS
permissions:
  contents: write

on:
  schedule:
    # Cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser markdownify openai requests

      - name: Run fetch script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/fetch.py

      - name: Commit & push new posts
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@example.com"
          git add _posts || true
          if git diff --cached --quiet; then
            echo "No new posts."
            exit 0
          fi
          git commit -m "bot: add new posts [skip ci]"
          git push
